[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

#[[main]]
#    identifier = "about"
#    name = "About me"
#    url = "/about"
#    weight = 2

#[[main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories"
#    weight = 3

#[[main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags"
#    weight = 4

#[[main]]
#    identifier = "donate"
#    name = "Donate"
#    url = "https://ko-fi.com/nixentric"
#    weight = 5

[[main]]
    identifier = "timeline"
    name = "Timeline"
    url = "/tags"
    weight = 6

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 7
    
# Social Media Configuration

#[[social]]
#    identifier = "twitter"
#    name = "Twitter"
#    url = "#"
#    weight = 1

#[[social]]
#    identifier = "instagram"
#    name = "Instagram"
#    url = "#"
#    weight = 2

[[social]]
    identifier = "email"
    name = "Email"
    url = "mailto:inkosizhong@gmail.com"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/InkosiZhong"
    weight = 3